language: node_js
node_js:
- node

services:
- postgresql

before_script:
- psql -c 'create database recipe_microservice_database_test;' -U postgres
- sequelize db:migrate --env test

script:
- npm install

after_script:
- npm test

deploy:
  provider: heroku
  api_key:
    secure: MNy/ufz/d2L04HglU64oxZWW1N72jKmiBTyNEYNE/0C9pUn/NAh22lnTVr0adKMgo4RatR4Pfmv4XOwgMDt75wyh9Ds2Zdx1wdKchm6/irGDfeG3Lb4/fEFfe/1xAbyCekCDKZqnNjTa7VHVgVtujxIGScDKUMXtP6Wn9cMqgFdq4/WSLDHRntueT/GSRdN/KJqXePeSN1vecgnIoCFHe82BZ2oRTcLMim5Oa78zBNlKWw7qdxr/6KP/ptUZ2s7Jwdy2Fi3aQOcZ5TSIwMmEuyZDMQviYhLkfnIylGCNIefsq4TCR4qWKiSpGHzWR28CTo7zuutUgzXciIcOnfrk2ou46JR2T0SEmip+ASUmFElVA6bxMpnGIpaeOVDArG4tTLN4pryerSbxPBXVYa2B10Q3BKLZyWBK3ekElZ1y93eggpEO1m5B25Ad+sicPOD64DOWp+o1tjPpecYmnrLU76o8nWDeP2lX0pBPPu1fQcaE5Iq3P0n7X7pH0o6CjAfK5x2lB0AklmZVjOwlm384F1o3o94As/dxQyOUVOoZ+qvibwtWOnNzcsriyoLxr4XlAz1wzsslWUoAQu8qHR8mULRS3JbAjJHtsjuJpuhL4rC9vK9S/nF5eAn5y1zXqBeBicyPryzSGl0Cpa5rxiktwYwwOmokOKMkzRLRweWxGL0=
  app: dry-peak-69368
  on:
    repo: froydroyce/recipe_microservice
